import {
  Store,
  Users,
  Star,
  CreditCard,
  PackageOpen,
  Truck,
  ClipboardList,
  ChartNoAxesCombined,
  UserCog,
  Clock3,
  Building2,
  Warehouse,
  Cloud,
  Smartphone,
  Bell,
  WalletCards,
  Tags,
  TicketPercent,
  RotateCcw,
  SlidersHorizontal,
  CalendarClock,
  ScanBarcode,
  LayoutDashboard,
  FileSpreadsheet,
  ReceiptText,
  ShoppingCart,
  ShoppingBag,
} from "lucide-react";

export const config = {
  title: "POS System",
  subtitle: "For shops, retail and service businesses",
  basePrice: 1500000,
  icon: Store,
};

export const basicFeatures = [
  "POS / Checkout",
  "Product Management",
  "Categories",
  "Cost Price + Selling Price",
  "Basic Inventory",
  "Automatic stock deduction",
  "Low-stock warning",
  "Cash Payment",
  "Discount",
  "Receipt Generation / Printing",
  "Sales History",
  "Basic Expenses",
  "Daily / Monthly Sales Report",
  "Basic Profit Report",
  "Top-selling Products",
  "Owner/Admin Account",
  "1–2 Cashier Accounts",
  "Basic Shop Settings",
  "Backup / Restore",
];

export const addons = [
  {
    id: "customer-management",
    icon: Users,
    title: "Customer Management",
    description:
      "Customer profiles, phone numbers, purchase history and notes.",
    price: 120000,
  },
  {
    id: "loyalty",
    icon: Star,
    title: "Loyalty / Points",
    description: "Reward points, membership levels and redeem points.",
    price: 200000,
  },
  {
    id: "credit-debt",
    icon: CreditCard,
    title: "Credit / Debt Management",
    description: "Customer debt, partial payments and outstanding balances.",
    price: 80000,
  },
  {
    id: "advanced-inventory",
    icon: PackageOpen,
    title: "Advanced Inventory",
    description:
      "Stock movement history, damaged/lost stock and stock adjustments.",
    price: 90000,
  },
  {
    id: "supplier-management",
    icon: Truck,
    title: "Supplier Management",
    description: "Supplier profiles, contact details and purchase history.",
    price: 170000,
  },
  {
    id: "purchase-management",
    icon: ClipboardList,
    title: "Purchase Management",
    description: "Purchase orders, stock purchases and cost records.",
    price: 80000,
  },
  {
    id: "advanced-reports",
    icon: ChartNoAxesCombined,
    title: "Advanced Reports",
    description:
      "Profit by product/category, sales comparison and inventory valuation.",
    price: 90000,
  },
  {
    id: "employee-management",
    icon: UserCog,
    title: "Employee Management",
    description: "Multiple employees, roles and detailed permissions.",
    price: 80000,
  },
  {
    id: "staff-attendance",
    icon: Clock3,
    title: "Staff Attendance",
    description: "Clock-in/out and attendance history.",
    price: 160000,
  },
  {
    id: "multi-branch",
    icon: Building2,
    title: "Multi-Branch",
    description: "Manage multiple shops or branches from one system.",
    price: 300000,
  },
  {
    id: "warehouse",
    icon: Warehouse,
    title: "Warehouse",
    description: "Separate warehouse stock and branch transfers.",
    price: 120000,
  },
  {
    id: "cloud-sync",
    icon: Cloud,
    title: "Cloud Sync",
    description: "Synchronize POS data securely to the cloud.",
    price: 100000,
  },
  {
    id: "owner-mobile-dashboard",
    icon: Smartphone,
    title: "Owner Mobile Dashboard",
    description: "View sales, stock and reports from a mobile device.",
    price: 300000,
  },
  {
    id: "remote-notifications",
    icon: Bell,
    title: "Remote Notifications",
    description: "Low-stock, high-sales and important remote alerts.",
    price: 60000,
  },
  {
    id: "advanced-payment-methods",
    icon: WalletCards,
    title: "Advanced Payment Methods",
    description: "KBZPay, WavePay, bank transfer and payment tracking.",
    price: 70000,
  },
  {
    id: "promotion-system",
    icon: Tags,
    title: "Promotion System",
    description: "Buy 1 Get 1, percentage promotions and scheduled discounts.",
    price: 170000,
  },
  {
    id: "coupon-voucher",
    icon: TicketPercent,
    title: "Coupon / Voucher",
    description: "Coupon codes, gift vouchers and redemption tracking.",
    price: 160000,
  },
  {
    id: "returns-refunds",
    icon: RotateCcw,
    title: "Returns & Refunds",
    description: "Product returns, refunds and exchange records.",
    price: 160000,
  },
  {
    id: "product-variants",
    icon: SlidersHorizontal,
    title: "Product Variants",
    description: "Size, color, model and other product variations.",
    price: 70000,
  },
  {
    id: "expiry-tracking",
    icon: CalendarClock,
    title: "Expiry Tracking",
    description: "Expiry dates and near-expiry warnings.",
    price: 65000,
  },

  {
    id: "business-dashboard",
    icon: LayoutDashboard,
    title: "Business Dashboard",
    description: "Detailed charts and business KPIs.",
    price: 190000,
  },
  {
    id: "excel-export",
    icon: FileSpreadsheet,
    title: "Excel Export",
    description: "Export sales, inventory and report data.",
    price: 40000,
  },
  {
    id: "custom-receipt",
    icon: ReceiptText,
    title: "Custom Receipt",
    description: "Custom receipt layout, logo and footer.",
    price: 40000,
  },
  {
    id: "ecommerce-integration",
    icon: ShoppingCart,
    title: "E-commerce Integration",
    description: "Connect POS stock and orders with an online shop.",
    price: 200000,
  },
  {
    id: "online-ordering",
    icon: ShoppingBag,
    title: "Online Ordering",
    description: "Customer online ordering connected directly to the POS.",
    price: 160000,
  },
];
